### ISSUE TITLE
Phishing Website Detection

### ISSUE THREAD

**Issue by AbhishekRP2002** [World-of-ML/DL-Simplified#61] opened 2022-08-04 15:55 UTC
### Deep Learning Simplified Repository (Proposing new issue)
:red_circle: **Project Title** :  Phishing Website Detection</br>
:red_circle: **Aim** : The candidates have to read the data and create a model baased on the data analysis to identify if the website is legitimate or a phishing . The Result will be detrmined by the two values [-1,1], where 1 represent Legitimate website and -1 represnets phishing.</br>
:red_circle: **Dataset** : https://www.kaggle.com/datasets/akashkr/phishing-website-dataset</br>
:red_circle: **Approach** : Try to use 3-4 algorithms to implement the models and compare all the algorithms to find out the best fitted algorithm for the model by checking the accuracy scores. Also do not forget to do a exploratory data analysis before creating any model.

**********************************************************************************
### 📍 **Follow the Guidelines to Contribute in the Project :**
* You need to create a separate folder named as the Project Title.
* Inside that folder, there will be four main components.
   * Images - To store the required images.
   * Dataset - To store the dataset or, information/source about the dataset.
   * Model - To store the machine learning model you've created using the dataset.
   * `requirements.txt` - This file will contain the required packages/libraries to run the project in other machines.
* Inside the `Model` folder, the `README.md` file must be filled up properly, with proper visualizations and conclusions.

***********************************************************************
:red_circle::yellow_circle: **Points to Note :**

- The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.
- "Issue Title" and "PR Title should be the same. Include issue number along with it.
- Follow Contributing Guidelines & Code of Conduct before start Contributing.

***********************************************************************
:white_check_mark: **To be Mentioned while taking the issue :**
- Full name :
- GitHub Profile Link : 
- Email ID :
- Participant ID (if applicable):
- Approach for this Project :
- What is your participant role? (Mention the Open Source program)

*************************************************************
Happy Contributing 🚀 

All the best. Enjoy your open source journey ahead. 😎

**Comment by AbhishekRP2002** [comment] 2022-08-04 15:55
I would like to work on this .

**Comment by abhisheks008** [comment] 2022-08-04 16:23
Okay go for it. @AbhishekRP2002

**Comment by abhisheks008** [comment] 2022-08-14 12:08
@AbhishekRP2002 updates please.

**Comment by abhisheks008** [comment] 2022-08-30 07:23
Updates please @AbhishekRP2002

**Comment by abhisheks008** [comment] 2022-09-24 04:05
@AbhishekRP2002 updates please.

**Comment by 5rushti** [comment] 2022-10-22 13:42
Full name : Srushti Killarikar
GitHub Profile Link : https://github.com/5rushti
Email ID : [khillarikarsrni19it@student.mes.ac.in](mailto:khillarikarsrni19it@student.mes.ac.in)
Approach for this Project : Planning to do EDA and use SVM, logistic regression, naive bayes etc

**Comment by abhisheks008** [comment] 2022-10-22 17:00
Which issue you wanna work on @5rushti? You can work on one issue at a time.

**Comment by 5rushti** [comment] 2022-10-23 06:18
i would like to work on phishing website detection

**Comment by abhisheks008** [comment] 2022-10-23 14:55
Issue assigned to you @5rushti. Use atleast few deep learning algorithms otherwise it'll be a normal machine learning project. You need to focus on deep learning ideas with this dataset.

**Comment by abhisheks008** [comment] 2022-11-17 08:44
Issue has been un-assigned from you due to inactivity.
@5rushti

**Comment by stiwari-ds** [comment] 2023-01-02 06:40
* Full name : **Siddhant Tiwari**
* GitHub Profile Link : https://github.com/stiwari-ds
* Email ID : siddhant.tiwari.ds@gmail.com
* Participant ID (if applicable): **s_tiwari** (Devfolio)
* Approach for this Project : 
    1. Feature selection/engineering through statistical tests.
    2. Setting a baseline score using ML algorithms (SVM/DecisionTree/GradientBoosting)
    3. Tune different neural network architectures to improve upon the baseline performance.
* What is your participant role? (Mention the Open Source program): Individual Contributor, **SWOC S3** (2023)

**Comment by abhisheks008** [comment] 2023-01-02 06:51
Waiting for the official confirmation from the SWOC team, as we do not have any channels for communicating with the participants and also didn't get any statement from the team itself. Issue will be assigned to you once the program officially starts.
@stiwari-ds

**Comment by stiwari-ds** [comment] 2023-01-02 06:56
@abhisheks008 Thank you. 
I have also not filled the project selection google form yet since they are adding projects few at a time (Deadline is 10th Jan, 2023). However this project was listed on SWOC S3 official website and I found it interesting, so I have claimed one issue in advance. Hope it is not a problem.

**Comment by abhisheks008** [comment] 2023-01-02 07:02
No issues on that. Thanks for showing up your interest in this project repository. Waiting for your contributions during this open source event.

**Comment by stiwari-ds** [comment] 2023-01-03 10:11
> Waiting for the official confirmation from the SWOC team, as we do not have any channels for communicating with the participants and also didn't get any statement from the team itself. Issue will be assigned to you once the program officially starts. @stiwari-ds

I have chosen Deep Learning Simplified as one of the projects for SWOC S3. So I would like to get started with this.
Please assign this issue to me.

**Comment by abhisheks008** [comment] 2023-01-03 16:20
Will assign you once we start our coding period.

**Comment by abhisheks008** [comment] 2023-01-08 14:03
One more thing, you are applying ML algos that's good. Try to use deep learning algos, coz this is a project repo for deep learning projects. Hope you understand.

Issue assigned to you. @stiwari-ds

**Comment by stiwari-ds** [comment] 2023-01-08 14:22
@abhisheks008 Thank you. I will get started with this.

I will be using an ML algorithm just establish a baseline score. After that my main focus will be on testing different neural network architectures to beat that score.

**Closed** 2023-01-16 04:11 UTC
Labels: Assigned :computer:, Medium, SWOC 2023
